/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.GUI;

import java.awt.event.MouseListener;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan Vykopal
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        spNewInvoice = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lbSystem = new javax.swing.JLabel();
        lbInvoice = new javax.swing.JLabel();
        lbCustomer = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbAddress = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        lbNumber = new javax.swing.JLabel();
        tfNumber = new javax.swing.JTextField();
        lbTown = new javax.swing.JLabel();
        tfTown = new javax.swing.JTextField();
        lbPSC = new javax.swing.JLabel();
        tfPSC = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lbProducts = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProducts = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lbPrice = new javax.swing.JLabel();
        lbSummary = new javax.swing.JLabel();
        btnCreateInvoice = new javax.swing.JButton();
        ftfDate = new javax.swing.JFormattedTextField();
        lbDate = new javax.swing.JLabel();
        btnAddRow = new javax.swing.JButton();
        btnRemoveRow = new javax.swing.JButton();
        spNewProduct = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        lbSystem2 = new javax.swing.JLabel();
        lbInvoice2 = new javax.swing.JLabel();
        lbCustomer2 = new javax.swing.JLabel();
        lbName2 = new javax.swing.JLabel();
        tfName2 = new javax.swing.JTextField();
        lbDescription = new javax.swing.JLabel();
        lbPrice2 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        btnCreateProduct = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        spNewCustomer = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        lbSystem1 = new javax.swing.JLabel();
        lbInvoice1 = new javax.swing.JLabel();
        lbCustomer1 = new javax.swing.JLabel();
        lbName1 = new javax.swing.JLabel();
        tfName1 = new javax.swing.JTextField();
        lbAddress1 = new javax.swing.JLabel();
        tfAddress1 = new javax.swing.JTextField();
        lbNumber1 = new javax.swing.JLabel();
        tfNumber1 = new javax.swing.JTextField();
        lbTown1 = new javax.swing.JLabel();
        tfTown1 = new javax.swing.JTextField();
        lbPSC1 = new javax.swing.JLabel();
        tfPSC1 = new javax.swing.JTextField();
        btnCreateCustomer = new javax.swing.JButton();
        spEditCustomer = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        lbSystem3 = new javax.swing.JLabel();
        lbInvoice3 = new javax.swing.JLabel();
        lbCustomer3 = new javax.swing.JLabel();
        lbName3 = new javax.swing.JLabel();
        tfName3 = new javax.swing.JTextField();
        lbAddress2 = new javax.swing.JLabel();
        tfAddress2 = new javax.swing.JTextField();
        lbNumber2 = new javax.swing.JLabel();
        tfNumber2 = new javax.swing.JTextField();
        lbTown2 = new javax.swing.JLabel();
        tfTown2 = new javax.swing.JTextField();
        lbPSC2 = new javax.swing.JLabel();
        tfPSC2 = new javax.swing.JTextField();
        btnFindCustomer = new javax.swing.JButton();
        lbCustomer5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnEditCustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCustomers = new javax.swing.JTable();
        spEditProduct = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        lbSystem4 = new javax.swing.JLabel();
        lbInvoice4 = new javax.swing.JLabel();
        lbCustomer6 = new javax.swing.JLabel();
        lbName5 = new javax.swing.JLabel();
        tfName5 = new javax.swing.JTextField();
        lbDescription1 = new javax.swing.JLabel();
        lbPrice3 = new javax.swing.JLabel();
        tfPrice1 = new javax.swing.JTextField();
        btnFindProduct = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        taDescription1 = new javax.swing.JTextArea();
        lbCustomer7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnEditProduct = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProducts2 = new javax.swing.JTable();
        spViewInvoice = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lbSystem5 = new javax.swing.JLabel();
        lbInvoice5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbInvoices = new javax.swing.JTable();
        btnChooseInvocie = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbInvoiceName = new javax.swing.JLabel();
        lbInvoiceAddress = new javax.swing.JLabel();
        lbInvoiceNumber = new javax.swing.JLabel();
        lbInvoiceTown = new javax.swing.JLabel();
        lbInvoicePSC = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbProducts3 = new javax.swing.JTable();
        lbCustomer4 = new javax.swing.JLabel();
        lbCustomer8 = new javax.swing.JLabel();
        lbCustomer9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbInvoicePrice = new javax.swing.JLabel();
        lbInvoiceDate = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miEnd = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miNewCustomer = new javax.swing.JMenuItem();
        miNewProduct = new javax.swing.JMenuItem();
        miNewInvoice = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miEditCustomer = new javax.swing.JMenuItem();
        miEditProduct = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miViewInovoice = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fakturačný systém");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1225, 855));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spNewInvoice.setBackground(new java.awt.Color(255, 255, 255));
        spNewInvoice.setAutoscrolls(true);
        spNewInvoice.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 1600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 1600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSystem.setFont(new java.awt.Font("Arial Narrow", 0, 40)); // NOI18N
        lbSystem.setText("Fakturačný systém");
        jPanel2.add(lbSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        lbInvoice.setFont(new java.awt.Font("Arial Narrow", 1, 30)); // NOI18N
        lbInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInvoice.setText("Vystavenie faktúry");
        jPanel2.add(lbInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 50));

        lbCustomer.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer.setText("Údaje zákazníka");
        jPanel2.add(lbCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 50));

        lbName.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbName.setText("Meno a Priezvisko:");
        jPanel2.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        tfName.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel2.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 310, -1));

        lbAddress.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbAddress.setText("Adresa:");
        jPanel2.add(lbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        tfAddress.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel2.add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 310, -1));

        lbNumber.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbNumber.setText("Číslo bydliska:");
        jPanel2.add(lbNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        tfNumber.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel2.add(tfNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 310, -1));

        lbTown.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbTown.setText("Mesto:");
        jPanel2.add(lbTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        tfTown.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel2.add(tfTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 310, -1));

        lbPSC.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbPSC.setText("PSČ:");
        jPanel2.add(lbPSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        tfPSC.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel2.add(tfPSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 310, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1340, 1200, 20));

        lbProducts.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProducts.setText("Zoznam fakturovaných tovarov");
        jPanel2.add(lbProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1200, 50));

        tbProducts.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tbProducts.getTableHeader().setFont(new java.awt.Font("Arial", 1, 20));
        tbProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Názov tovaru", "Opis Tovaru", "Množstvo", "Cena €", "Celkovo €"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProducts.setRowHeight(20);
        jScrollPane3.setViewportView(tbProducts);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 720, 1030, 380));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1200, 20));

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbPrice.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPrice.setText("0.00 €");
        jPanel3.add(lbPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 100, -1));
        lbPrice.getAccessibleContext().setAccessibleParent(this);

        lbSummary.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbSummary.setText("Celková suma");
        jPanel3.add(lbSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1220, 290, 90));

        btnCreateInvoice.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnCreateInvoice.setLabel("Vytvoriť faktúru");
        jPanel2.add(btnCreateInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1460, 200, -1));

        ftfDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        ftfDate.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel2.add(ftfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1390, 250, -1));

        lbDate.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbDate.setText("Dátum vystavenia:");
        jPanel2.add(lbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1390, -1, -1));

        btnAddRow.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnAddRow.setText("Pridať položku");
        jPanel2.add(btnAddRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1110, 290, -1));

        btnRemoveRow.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnRemoveRow.setText("Odobrať poslednú položku");
        jPanel2.add(btnRemoveRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 1170, 290, -1));

        spNewInvoice.setViewportView(jPanel2);

        getContentPane().add(spNewInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1215, -1));

        spNewProduct.setBackground(new java.awt.Color(255, 255, 255));
        spNewProduct.setAutoscrolls(true);
        spNewProduct.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(1200, 1600));
        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSystem2.setFont(new java.awt.Font("Arial Narrow", 0, 40)); // NOI18N
        lbSystem2.setText("Fakturačný systém");
        jPanel5.add(lbSystem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        lbInvoice2.setFont(new java.awt.Font("Arial Narrow", 1, 30)); // NOI18N
        lbInvoice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInvoice2.setText("Vytvorenie nového tovaru");
        jPanel5.add(lbInvoice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 50));

        lbCustomer2.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer2.setText("Údaje tovaru");
        jPanel5.add(lbCustomer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 50));

        lbName2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbName2.setText("Názov tovaru:");
        jPanel5.add(lbName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        tfName2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel5.add(tfName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 310, -1));

        lbDescription.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbDescription.setText("Popis:");
        jPanel5.add(lbDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        lbPrice2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbPrice2.setText("Cena:");
        jPanel5.add(lbPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, -1, -1));

        tfPrice.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel5.add(tfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 310, -1));

        btnCreateProduct.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnCreateProduct.setText("Vytvoriť nový tovar");
        jPanel5.add(btnCreateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 280, -1));

        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        taDescription.setLineWrap(true);
        taDescription.setRows(5);
        taDescription.setWrapStyleWord(true);
        jScrollPane5.setViewportView(taDescription);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 310, 200));

        spNewProduct.setViewportView(jPanel5);

        getContentPane().add(spNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        spNewCustomer.setBackground(new java.awt.Color(255, 255, 255));
        spNewCustomer.setAutoscrolls(true);
        spNewCustomer.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(1200, 1600));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSystem1.setFont(new java.awt.Font("Arial Narrow", 0, 40)); // NOI18N
        lbSystem1.setText("Fakturačný systém");
        jPanel4.add(lbSystem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        lbInvoice1.setFont(new java.awt.Font("Arial Narrow", 1, 30)); // NOI18N
        lbInvoice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInvoice1.setText("Vytvorenie nového zákazníka");
        jPanel4.add(lbInvoice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 50));

        lbCustomer1.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer1.setText("Údaje zákazníka");
        jPanel4.add(lbCustomer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 50));

        lbName1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbName1.setText("Meno a Priezvisko:");
        jPanel4.add(lbName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        tfName1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel4.add(tfName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 310, -1));

        lbAddress1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbAddress1.setText("Adresa:");
        jPanel4.add(lbAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        tfAddress1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel4.add(tfAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 310, -1));

        lbNumber1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbNumber1.setText("Číslo bydliska:");
        jPanel4.add(lbNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        tfNumber1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel4.add(tfNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 310, -1));

        lbTown1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbTown1.setText("Mesto:");
        jPanel4.add(lbTown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        tfTown1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel4.add(tfTown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 310, -1));

        lbPSC1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbPSC1.setText("PSČ:");
        jPanel4.add(lbPSC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        tfPSC1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel4.add(tfPSC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 310, -1));

        btnCreateCustomer.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnCreateCustomer.setText("Vytvoriť nového zázkazníka");
        jPanel4.add(btnCreateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 280, -1));

        spNewCustomer.setViewportView(jPanel4);

        getContentPane().add(spNewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        spEditCustomer.setBackground(new java.awt.Color(255, 255, 255));
        spEditCustomer.setAutoscrolls(true);
        spEditCustomer.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(1200, 1600));
        jPanel6.setPreferredSize(new java.awt.Dimension(1200, 1100));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSystem3.setFont(new java.awt.Font("Arial Narrow", 0, 40)); // NOI18N
        lbSystem3.setText("Fakturačný systém");
        jPanel6.add(lbSystem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        lbInvoice3.setFont(new java.awt.Font("Arial Narrow", 1, 30)); // NOI18N
        lbInvoice3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInvoice3.setText("Úprava informácií o zákazníkovi");
        jPanel6.add(lbInvoice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 50));

        lbCustomer3.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer3.setText("Údaje zákazníka");
        jPanel6.add(lbCustomer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1200, 50));

        lbName3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbName3.setText("Meno a Priezvisko:");
        jPanel6.add(lbName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, -1, -1));

        tfName3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel6.add(tfName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 310, -1));

        lbAddress2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbAddress2.setText("Adresa:");
        jPanel6.add(lbAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 760, -1, -1));

        tfAddress2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel6.add(tfAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 750, 310, -1));

        lbNumber2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbNumber2.setText("Číslo bydliska:");
        jPanel6.add(lbNumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 840, -1, -1));

        tfNumber2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel6.add(tfNumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 830, 310, -1));

        lbTown2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbTown2.setText("Mesto:");
        jPanel6.add(lbTown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 910, -1, -1));

        tfTown2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel6.add(tfTown2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 900, 310, -1));

        lbPSC2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbPSC2.setText("PSČ:");
        jPanel6.add(lbPSC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 990, -1, -1));

        tfPSC2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel6.add(tfPSC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 980, 310, -1));

        btnFindCustomer.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnFindCustomer.setText("Vybrať zákazníka");
        jPanel6.add(btnFindCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 330, -1));

        lbCustomer5.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer5.setText("Výber zákazníka");
        jPanel6.add(lbCustomer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1200, 50));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1200, 20));

        btnEditCustomer.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnEditCustomer.setText("Upraviť údaje zákazníka");
        jPanel6.add(btnEditCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1050, 330, -1));

        tbCustomers.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tbCustomers.getTableHeader().setFont(new java.awt.Font("Arial", 1, 20));
        tbCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meno a Priezvisko", "Adresa", "Číslo", "Mesto", "PSČ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCustomers.setRowHeight(20);
        jScrollPane1.setViewportView(tbCustomers);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 960, 300));

        spEditCustomer.setViewportView(jPanel6);

        getContentPane().add(spEditCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1215, -1));

        spEditProduct.setBackground(new java.awt.Color(255, 255, 255));
        spEditProduct.setAutoscrolls(true);
        spEditProduct.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(1200, 1600));
        jPanel7.setPreferredSize(new java.awt.Dimension(1200, 1200));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSystem4.setFont(new java.awt.Font("Arial Narrow", 0, 40)); // NOI18N
        lbSystem4.setText("Fakturačný systém");
        jPanel7.add(lbSystem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        lbInvoice4.setFont(new java.awt.Font("Arial Narrow", 1, 30)); // NOI18N
        lbInvoice4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInvoice4.setText("Úprava existujúceho tovaru");
        jPanel7.add(lbInvoice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 50));

        lbCustomer6.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer6.setText("Údaje tovaru");
        jPanel7.add(lbCustomer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1200, 50));

        lbName5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbName5.setText("Názov tovaru:");
        jPanel7.add(lbName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 720, -1, -1));

        tfName5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel7.add(tfName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 710, 310, -1));

        lbDescription1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbDescription1.setText("Popis:");
        jPanel7.add(lbDescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 800, -1, -1));

        lbPrice3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbPrice3.setText("Cena:");
        jPanel7.add(lbPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1050, -1, -1));

        tfPrice1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel7.add(tfPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 1040, 310, -1));

        btnFindProduct.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnFindProduct.setText("Vybrať tovar");
        jPanel7.add(btnFindProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 280, -1));

        taDescription1.setColumns(20);
        taDescription1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        taDescription1.setLineWrap(true);
        taDescription1.setRows(5);
        taDescription1.setWrapStyleWord(true);
        jScrollPane6.setViewportView(taDescription1);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 800, 310, 190));

        lbCustomer7.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer7.setText("Výber tovaru");
        jPanel7.add(lbCustomer7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1200, 50));
        jPanel7.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1210, 20));

        btnEditProduct.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnEditProduct.setText("Upraviť existujúci tovar");
        jPanel7.add(btnEditProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1130, 280, -1));

        tbProducts2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tbProducts2.getTableHeader().setFont(new java.awt.Font("Arial", 1, 20));
        tbProducts2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Názov", "Popis", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProducts2.setRowHeight(20);
        jScrollPane2.setViewportView(tbProducts2);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 960, 300));

        spEditProduct.setViewportView(jPanel7);

        getContentPane().add(spEditProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1215, -1));

        spViewInvoice.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 1500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSystem5.setFont(new java.awt.Font("Arial Narrow", 0, 40)); // NOI18N
        lbSystem5.setText("Fakturačný systém");
        jPanel1.add(lbSystem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        lbInvoice5.setFont(new java.awt.Font("Arial Narrow", 1, 30)); // NOI18N
        lbInvoice5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInvoice5.setText("Zobrazenie faktúry");
        jPanel1.add(lbInvoice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 50));

        tbInvoices.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tbInvoices.getTableHeader().setFont(new java.awt.Font("Arial", 1, 20));
        tbInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dátum", "Suma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbInvoices.setRowHeight(20);
        jScrollPane4.setViewportView(tbInvoices);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 1030, 380));

        btnChooseInvocie.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnChooseInvocie.setText("Zobraz faktúru");
        jPanel1.add(btnChooseInvocie, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 200, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1210, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Meno a Priezvisko:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 780, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Adresa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 840, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Číslo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 900, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("Mesto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 950, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("PSČ:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1000, -1, -1));

        lbInvoiceName.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lbInvoiceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 780, 240, 30));

        lbInvoiceAddress.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lbInvoiceAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 840, 240, 30));

        lbInvoiceNumber.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lbInvoiceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 900, 250, 30));

        lbInvoiceTown.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lbInvoiceTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 950, 250, 30));

        lbInvoicePSC.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lbInvoicePSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1000, 290, 30));

        tbProducts3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tbProducts3.getTableHeader().setFont(new java.awt.Font("Arial", 1, 20));
        tbProducts3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Názov", "Popis", "Cena", "Množstvo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProducts3.setRowHeight(20);
        jScrollPane7.setViewportView(tbProducts3);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1130, 910, 250));

        lbCustomer4.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer4.setText("Fakturované tovary");
        jPanel1.add(lbCustomer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1060, 1200, 50));

        lbCustomer8.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer8.setText("Výber faktúry");
        jPanel1.add(lbCustomer8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 50));

        lbCustomer9.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lbCustomer9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCustomer9.setText("Údaje zákazníka");
        jPanel1.add(lbCustomer9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1200, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel6.setText("Dátum vystavenia:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel7.setText("Celková suma:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1400, -1, -1));

        lbInvoicePrice.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lbInvoicePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1400, 240, 30));

        lbInvoiceDate.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jPanel1.add(lbInvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1450, 210, 30));

        spViewInvoice.setViewportView(jPanel1);

        getContentPane().add(spViewInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1215, -1));

        jMenu1.setText("Súbor");

        miEnd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miEnd.setText("Koniec");
        jMenu1.add(miEnd);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Upraviť");

        miNewCustomer.setText("Vytvorenie zákazníka");
        jMenu2.add(miNewCustomer);

        miNewProduct.setText("Vytvorenie tovaru");
        jMenu2.add(miNewProduct);

        miNewInvoice.setText("Vytvorenie faktúry");
        jMenu2.add(miNewInvoice);
        jMenu2.add(jSeparator2);

        miEditCustomer.setText("Upraviť existujúceho zázkazníka");
        jMenu2.add(miEditCustomer);

        miEditProduct.setText("Upraviť existujúci tovar");
        jMenu2.add(miEditProduct);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Zobraziť");

        miViewInovoice.setText("Zobraziť faktúry");
        jMenu4.add(miViewInovoice);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Pomocník");

        miAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miAbout.setText("O autorovi");
        jMenu3.add(miAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRow;
    private javax.swing.JButton btnChooseInvocie;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnCreateInvoice;
    private javax.swing.JButton btnCreateProduct;
    private javax.swing.JButton btnEditCustomer;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnFindCustomer;
    private javax.swing.JButton btnFindProduct;
    private javax.swing.JButton btnRemoveRow;
    private javax.swing.JFormattedTextField ftfDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAddress1;
    private javax.swing.JLabel lbAddress2;
    private javax.swing.JLabel lbCustomer;
    private javax.swing.JLabel lbCustomer1;
    private javax.swing.JLabel lbCustomer2;
    private javax.swing.JLabel lbCustomer3;
    private javax.swing.JLabel lbCustomer4;
    private javax.swing.JLabel lbCustomer5;
    private javax.swing.JLabel lbCustomer6;
    private javax.swing.JLabel lbCustomer7;
    private javax.swing.JLabel lbCustomer8;
    private javax.swing.JLabel lbCustomer9;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbDescription1;
    private javax.swing.JLabel lbInvoice;
    private javax.swing.JLabel lbInvoice1;
    private javax.swing.JLabel lbInvoice2;
    private javax.swing.JLabel lbInvoice3;
    private javax.swing.JLabel lbInvoice4;
    private javax.swing.JLabel lbInvoice5;
    private javax.swing.JLabel lbInvoiceAddress;
    private javax.swing.JLabel lbInvoiceDate;
    private javax.swing.JLabel lbInvoiceName;
    private javax.swing.JLabel lbInvoiceNumber;
    private javax.swing.JLabel lbInvoicePSC;
    private javax.swing.JLabel lbInvoicePrice;
    private javax.swing.JLabel lbInvoiceTown;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbName3;
    private javax.swing.JLabel lbName5;
    private javax.swing.JLabel lbNumber;
    private javax.swing.JLabel lbNumber1;
    private javax.swing.JLabel lbNumber2;
    private javax.swing.JLabel lbPSC;
    private javax.swing.JLabel lbPSC1;
    private javax.swing.JLabel lbPSC2;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbPrice2;
    private javax.swing.JLabel lbPrice3;
    private javax.swing.JLabel lbProducts;
    private javax.swing.JLabel lbSummary;
    private javax.swing.JLabel lbSystem;
    private javax.swing.JLabel lbSystem1;
    private javax.swing.JLabel lbSystem2;
    private javax.swing.JLabel lbSystem3;
    private javax.swing.JLabel lbSystem4;
    private javax.swing.JLabel lbSystem5;
    private javax.swing.JLabel lbTown;
    private javax.swing.JLabel lbTown1;
    private javax.swing.JLabel lbTown2;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miEditCustomer;
    private javax.swing.JMenuItem miEditProduct;
    private javax.swing.JMenuItem miEnd;
    private javax.swing.JMenuItem miNewCustomer;
    private javax.swing.JMenuItem miNewInvoice;
    private javax.swing.JMenuItem miNewProduct;
    private javax.swing.JMenuItem miViewInovoice;
    private javax.swing.JScrollPane spEditCustomer;
    private javax.swing.JScrollPane spEditProduct;
    private javax.swing.JScrollPane spNewCustomer;
    private javax.swing.JScrollPane spNewInvoice;
    private javax.swing.JScrollPane spNewProduct;
    private javax.swing.JScrollPane spViewInvoice;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextArea taDescription1;
    private javax.swing.JTable tbCustomers;
    private javax.swing.JTable tbInvoices;
    private javax.swing.JTable tbProducts;
    private javax.swing.JTable tbProducts2;
    private javax.swing.JTable tbProducts3;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAddress1;
    private javax.swing.JTextField tfAddress2;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfName1;
    private javax.swing.JTextField tfName2;
    private javax.swing.JTextField tfName3;
    private javax.swing.JTextField tfName5;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfNumber1;
    private javax.swing.JTextField tfNumber2;
    private javax.swing.JTextField tfPSC;
    private javax.swing.JTextField tfPSC1;
    private javax.swing.JTextField tfPSC2;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfPrice1;
    private javax.swing.JTextField tfTown;
    private javax.swing.JTextField tfTown1;
    private javax.swing.JTextField tfTown2;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JButton getBtnCreateCustomer() {
        return btnCreateCustomer;
    }

    public javax.swing.JButton getBtnCreateInvoice() {
        return btnCreateInvoice;
    }

    public javax.swing.JButton getBtnCreateProduct() {
        return btnCreateProduct;
    }

    public String getFtfDate() {
        return ftfDate.getText().trim();
    }

    public javax.swing.JMenuItem getMiEditCustomer() {
        return miEditCustomer;
    }

    public javax.swing.JMenuItem getMiEditProduct() {
        return miEditProduct;
    }

    public javax.swing.JMenuItem getMiEnd() {
        return miEnd;
    }

    public javax.swing.JMenuItem getMiNewCustomer() {
        return miNewCustomer;
    }

    public javax.swing.JMenuItem getMiNewInvoice() {
        return miNewInvoice;
    }

    public javax.swing.JMenuItem getMiNewProduct() {
        return miNewProduct;
    }

    public JMenuItem getMiAbout() {
        return miAbout;
    }

    public void setMiAbout(JMenuItem miAbout) {
        this.miAbout = miAbout;
    }
    
    public String getTfAddress() {
        return tfAddress.getText().trim();
    }

    public String getTfAddress1() {
        return tfAddress1.getText().trim();
    }

    public String getTfName() {
        return tfName.getText().trim();
    }

    public String getTfName1() {
        return tfName1.getText().trim();
    }

    public String getTfName2() {
        return tfName2.getText().trim();
    }

    public String getTfNumber() {
        return tfNumber.getText().trim();
    }

    public String getTfNumber1() {
        return tfNumber1.getText().trim();
    }

    public String getTfNumber2() {
        return tfNumber2.getText().trim();
    }

    public String getTfPSC() {
        return tfPSC.getText().trim();
    }

    public String getTfPSC1() {
        return tfPSC1.getText().trim();
    }

    public String getTfTown() {
        return tfTown.getText().trim();
    }

    public String getTfTown1() {
        return tfTown1.getText().trim();
    }

    public javax.swing.JTextArea getjTextArea1() {
        return taDescription;
    }

    public void setLbPrice(String text) {
        this.lbPrice.setText(text);
    }

    public javax.swing.JScrollPane getSpNewCustomer() {
        return spNewCustomer;
    }

    public javax.swing.JScrollPane getSpNewInvoice() {
        return spNewInvoice;
    }

    public javax.swing.JScrollPane getSpNewProduct() {
        return spNewProduct;
    }
    
    public String getTaDescription() {
        return taDescription.getText().trim();
    }
 
    public double getTfPrice() {
        try {
            if (tfPrice.getText().equals("")) {
                return 0;
            }
            return Double.parseDouble(tfPrice.getText());
        } catch (NumberFormatException e) {
            System.out.println("Chyba nesprávny formát!");
            JOptionPane.showMessageDialog(rootPane, "Nesprávny formát ceny! Ako desatiiný oddelovač sa využíva '.' !");
        }
        
        return -1;
    }

    public javax.swing.JButton getBtnFindCustomer() {
        return btnFindCustomer;
    }

    public javax.swing.JScrollPane getSpEditCustomer() {
        return spEditCustomer;
    }
 
    public javax.swing.JScrollPane getSpEditProduct() {
        return spEditProduct;
    }

    public javax.swing.table.DefaultTableModel getTbProductsModel() {
        return (DefaultTableModel) tbProducts.getModel();
    }

    public String getTfAddress2() {
        return tfAddress2.getText().trim();
    }
  
    public String getTfPSC2() {
        return tfPSC2.getText().trim();
    }

    public String getTfTown2() {
        return tfTown2.getText().trim();
    }

    public void setTfPSC2(String tfPSC2) {
        this.tfPSC2.setText(tfPSC2);
    }
  
    public void setTfName1(String text) {
        this.tfName1.setText(text);
    }
    
    public void setTfAddress1(String text) {
        this.tfAddress1.setText(text);
    }

    public void setTfNumber1(String text) {
        this.tfNumber1.setText(text);
    }
 
    public void setTfTown1(String text) {
        this.tfTown1.setText(text);
    }
    
    public void setTfPSC1(String text) {
        this.tfPSC1.setText(text);
    }
    
    public void setTfName2(String text) {
        this.tfName2.setText(text);
    }

    public void setTaDescription(String text) {
        this.taDescription.setText(text);
    }

    public void setTfPrice(String text) {
        this.tfPrice.setText(text);
    }

    public void setTfTown2(String tfTown2) {
        this.tfTown2.setText(tfTown2);
    }
   
    public void setTfAddress2(String tfAddress2) {
        this.tfAddress2.setText(tfAddress2);
    }
    
    public void setTfNumber2(String tfNumber2) {
        this.tfNumber2.setText(tfNumber2);
    }

    public javax.swing.JButton getBtnFindProduct() {
        return btnFindProduct;
    }

    public String getTaDescription1() {
        return taDescription1.getText();
    }

    public String getTfName3() {
        return tfName3.getText();
    }

    public String getTfName5() {
        return tfName5.getText();
    }

    public double getTfPrice1() {
        try {
            if (tfPrice1.getText().equals("")) {
                return 0;
            }
            return Double.parseDouble(tfPrice1.getText());
        } catch (NumberFormatException e) {
            System.out.println("Chyba nesprávny formát!");
            JOptionPane.showMessageDialog(rootPane, "Nesprávny formát ceny! Ako desatiiný oddelovač sa využíva '.' !");
        }
        
        return -1;
    }

    public void setTaDescription1(String text) {
        this.taDescription1.setText(text);
    }

    public void setTfName3(String text) {
        this.tfName3.setText(text);
    }

    public void setTfName5(String text) {
        this.tfName5.setText(text);
    }
    public void setTfPrice1(String text) {
        this.tfPrice1.setText(text);
    }

    public javax.swing.JButton getBtnEditCustomer() {
        return btnEditCustomer;
    }

    public javax.swing.JButton getBtnEditProduct() {
        return btnEditProduct;
    }

    public javax.swing.JButton getBtnAddRow() {
        return btnAddRow;
    }
    
    public javax.swing.JButton getBtnRemoveRow() {
        return btnRemoveRow;
    }
    
    public void setTfName(String text){
        this.tfName.setText(text);
    }
    
    public void setTfAddress(String text) {
        this.tfAddress.setText(text);
    }
    
    public void setTfNumber(String text) {
        this.tfNumber.setText(text);
    }
    
    public void setTfTown(String text) {
        this.tfTown.setText(text);
    }
 
    public void setTfPSC(String text){
        this.tfPSC.setText(text);
    }
    
    public void setFtfDate(String text) {
        this.ftfDate.setText(text);
    }

    public javax.swing.table.DefaultTableModel getTbCustomersModel() {
        return (DefaultTableModel) tbCustomers.getModel();
    }
    
    public javax.swing.JTable getTbCustomersTable() {
        return tbCustomers;
    }

    public javax.swing.table.DefaultTableModel getTbProducts2Model() {
        return (DefaultTableModel) tbProducts2.getModel();
    }
    
    public javax.swing.JTable getTbProducts2Table() {
        return tbProducts2;
    }

    public javax.swing.JButton getBtnChooseInvocie() {
        return btnChooseInvocie;
    }

    public javax.swing.JScrollPane getSpViewInvoice() {
        return spViewInvoice;
    }
    
    public DefaultTableModel getTbCustomersModel2() {
        return (DefaultTableModel) tbCustomers.getModel();
    }

    public javax.swing.JTable getTbInvoices() {
        return tbInvoices;
    }
    
    public DefaultTableModel getTbProductsModel3() {
        return (DefaultTableModel) tbProducts3.getModel();
    }
    
    public DefaultTableModel getTbInvoicesModel() {
        return (DefaultTableModel) tbInvoices.getModel();
    }

    public void setLbInvoiceAddress(String text) {
        this.lbInvoiceAddress.setText(text);
    }

    public void setLbInvoiceDate(String text) {
        this.lbInvoiceDate.setText(text);
    }

    public void setLbInvoiceName(String text) {
        this.lbInvoiceName.setText(text);
    }

    public void setLbInvoiceNumber(String text) {
        this.lbInvoiceNumber.setText(text);
    }

    public void setLbInvoicePSC(String text) {
        this.lbInvoicePSC.setText(text);
    }

    public void setLbInvoicePrice(String text) {
        this.lbInvoicePrice.setText(text);
    }

    public void setLbInvoiceTown(String text) {
        this.lbInvoiceTown.setText(text);
    }

    public javax.swing.JMenuItem getMiViewInvoices() {
        return miViewInovoice;
    }
    
    /**
     * Táto metóda vymaže zo všetkých tlačidiel všetky MouseListenery.
     */
    public void removeListeners() {
        for (MouseListener ml : btnAddRow.getMouseListeners()) {
            btnAddRow.removeMouseListener(ml);
        }
        for (MouseListener ml : btnChooseInvocie.getMouseListeners()) {
            btnChooseInvocie.removeMouseListener(ml);
        }
        for (MouseListener ml : btnCreateCustomer.getMouseListeners()) {
            btnCreateCustomer.removeMouseListener(ml);
        }
        for (MouseListener ml : btnCreateInvoice.getMouseListeners()) {
            btnCreateInvoice.removeMouseListener(ml);
        }
        for (MouseListener ml : btnCreateProduct.getMouseListeners()) {
            btnCreateProduct.removeMouseListener(ml);
        }
        for (MouseListener ml : btnEditCustomer.getMouseListeners()) {
            btnEditCustomer.removeMouseListener(ml);
        }
        for (MouseListener ml : btnEditProduct.getMouseListeners()) {
            btnEditProduct.removeMouseListener(ml);
        }
        for (MouseListener ml : btnFindCustomer.getMouseListeners()) {
            btnFindCustomer.removeMouseListener(ml);
        }
        for (MouseListener ml : btnFindProduct.getMouseListeners()) {
            btnFindProduct.removeMouseListener(ml);
        }
        for (MouseListener ml : btnRemoveRow.getMouseListeners()) {
            btnRemoveRow.removeMouseListener(ml);
        }
    }
    
}
